### ISSUE TITLE
Merge n-instrumentation in to o-tracking

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-tracking#93]
- [x] o-grid/o-viewport - decorate all events with current layout and orientation https://github.com/Financial-Times/n-third-party-code/blob/master/src/analytics/o-tracking-wrapper.js
- [x] copy - to be migrated unchanged. Look into Tynt's functionality to make sure the events o-tracking sends could, in theory, be generated by tynt if we need to swap it in in future
- [x] scroll depth - track 10, 20 etc percentiles by default. Add ability to declaratively specify an element is interesting to track scroll for using attributes `data-o-tracking--scroll-bottom`, `data-o-tracking--scroll-top`. Use o-viewport to throttle scroll events
- [x] nav timing - bundle with page view event if possible
- [x] attention time - port implementation from https://github.com/Financial-Times/next-js-setup/commit/ee489d92c99d0c9ba864ca0ac38d76b1f3b1b853
- [x] domPath - propose a middle ground between next's terse, human readable domPaths and origami's hashed, xpath based element id's for identifying where on the page an element is. 
- [x] Try to unify link and cta tracking
- [x] mouse tracking - Consider tracking physical location of clicks https://github.com/Financial-Times/n-instrumentation/pull/17
- [x] use o-viewport for visibility https://github.com/Financial-Times/o-viewport/issues/25

@markstephens @alicebartlett @triblondon @commuterjoy

**Comment by commuterjoy** [comment]
> Look into Tynt's functionality to make sure the events
> o-tracking sends could, in theory, be generated by tynt if we need to swap it in in future

on next I don't think we want Tynt directly to be manipulating URLs etc. or sending events.

> human readable domPaths

please, please keep something usable and understandable to 99% of the population :)

**Comment by wheresrhys** [comment]
Dependent on
- https://github.com/Financial-Times/o-grid
- https://github.com/Financial-Times/polyfill-service/pull/536
- https://github.com/Financial-Times/o-viewport/issues/25 (sort of)

**Comment by wheresrhys** [comment]
So here's my domPath/element id proposal

## Config
- includeAllNodes (Bool) - whether to include every dom node in the element genertaed id (if false only includes nodes with data-trackable attributes) [default false]

If the above is true then id's will be the result of traversing the DOM, including sibling index. Not recommended at all!

If the above is false the following attributes can be put in the DOM

## Attributes
 - data-o-trackable-name - name to identify an element by (data-o-component is also used if present. if both are present then concatenated with a ':')
 - data-o-trackable-collection 
 When we want to know the sibling index of a component it's not always easy as perhaps the component is wrapped in a tree of elements, and only the top level one has siblings (e.g. named links, which are each contained in an li). When a `data-o-trackable-collection` attribute is encountered the sibling index of the next named element in the dom path is calculated based on the index of the child of `data-o-trackable-collection` that contains the target. Indexes begin at 1.
 - aria-attributes on any named items are also sent
 - if the target of the click is not named, but it is a natively clickable element (e.g link, button) then a name is generated based on attributes such as href, name, id
 - the node type of the target is always included

## Examples

```
<div data-o-component="comments">
	<ul>
		<li data-o-trackable-name="comment">...</li>
		<li data-o-trackable-name="comment">
			<button data-o-trackable-name="edit" aria-pressed="true">edit</button>
		</li>
	</ul>
</div>
```

id of button = `o-comments|comment|button:edit[pressed]`

```
<div data-o-component="comments" data-o-trackable-name="article-chat">
	<ul data-o-trackable-collection>
		<li data-o-trackable-name="comment">...</li>
		<li data-o-trackable-name="comment">
			<a href="http://www.wallaby-sanctua.ry/spam">link jacked</a>
		</li>
	</ul>
</div>
```

id of link = `o-comments:article-chat|comment[2]|a:www.wallaby-sanctua.ry/spam`

**Comment by wheresrhys** [comment]
More thoughts on the above
 - href (and analysis of) should be a separate attribute, and not bundled in with the element id
 - both the full path and terse, intelligent one should be generated for each click. May as well

**Comment by AlbertoElias** [comment]
If we were to go with this, I'd say the attributes should be called `o-tracking-name` for example, to follow the spec. 

I'd say the `[2]` should go before the name if each `<a>` can have a different name. If we expect them all to be named the same way in all cases, it can go after.

Why would you generate both paths?

**Comment by wheresrhys** [comment]
yep, will change names

Here's a new adjusted proposal (followed by explanation), largely the same as above but just showing example output
```
{
  context: {
     domPath: 'div[0]|div[2]|article[1]#main|p[3]|div[1]|a[2]',
     thinkOfANameForThis: 'main-article|o-more-ons|related-article[2]',
     nodeName: 'a',
     href: 'https://next.ft.com/cotent/231984123grqwuyyr329mfwyt'
  }
```

The reason for outputting both styles of dom path is 
a) it's cheap as we're traversing the dom anyway
b) it means we don't have to bother ourselves with deciding how to combine nodeName, id etc. with o-tracking  attributes - both kinds of data are available in a clear easy to describe way
c) we could make it configurable whether to output one style or the other or both.

**Comment by AlbertoElias** [comment]
I'd rather just support what there's a use case for. If there is for having both paths, then great

**Comment by wheresrhys** [comment]
the basic domPath is for using o-tracking on existing sites where markup won't contain data-o-tracking attributes. domPath is also guaranteed to be unique, whereas the second isn't (though if the dev is using the attributes properly, it will be unique)

**Comment by markstephens** [comment]
@wheresrhys 

Can we keep some of the separate from o-tracking in another module?
I would rather have a separate module as o-tracking will go out on many products, some are third party, and it won’t necessarily make sense to have this stuff within o-tracking.

I get some of it will need to be in o-tracking for consistency. What are the options?

**Comment by AlbertoElias** [comment]
We already have o-element-visibility, so I'm fine with separating some
things to smaller module. I think that was the original idea

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by markstephens** [comment]
Only other thing to note after a quick scan of the thread,

With reference to https://github.com/Financial-Times/o-tracking/issues/93#issuecomment-162468811
o-tracking includes the source id and link title, so, these need to be maintained.

Example:
```json
"context":{  
   "link":{  
      "id":"body/div/nav/ol/li/a/world-uk",
      "source_id":"cihxbkd5300003j73xxmrd5zk",
      "href":"http://www.ft.com/world/uk",
      "title":"UK"
   }
}
```

**Comment by wheresrhys** [comment]
Which stuff in particular should go in here and which in another component (please refer to the list at the top of this thread)

**Comment by wheresrhys** [comment]
Idea for turning enhanced tracking features on/off

e.g.
```
oTracking.init({
   scrollDepth: false /// default
})

or 
- `true` - on for everyone
- `0.15` - on for 15% of people
- `function () {return bool}` - control who it's on for

cc @commuterjoy

**Comment by AlbertoElias** [comment]
Just a mention that for the xpath, I think we should use the data attribute `data-o-tracking-track`. I think it's something that should be up to products and modules mustn't use it

**Comment by markstephens** [comment]
I would still like a fallback so that the tracking works without these tags.
There have been *so* many times in the past where we're not tracking
something and someone want's stats on it.

o-tracking link tracking automatically works for all links at the mo, by
doing otracking.link.init()


--
Mark Stephens
BI Solutions Architect
Financial Times Ltd ft.com
Email: mark.stephens@ft.com
Int Ext: 4251
Tel: 020 7873 4251

<https://www.facebook.com/financialtimes> <https://twitter.com/FT>
<http://www.linkedin.com/company/financial-times>
<https://plus.google.com/+FinancialTimes/posts>
<http://www.youtube.com/user/FinancialTimesVideos>

On 21 January 2016 at 14:24, Alberto Elias <notifications@github.com> wrote:

> Just a mention that for the xpath, I think we should use the data
> attribute data-o-tracking-track. I think it's something that should be up
> to products and modules mustn't use it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-tracking/issues/93#issuecomment-173583809>
> .
>

-- 

------------------------------

*This email was sent by a company owned by Financial Times Group Limited 
("FT Group <http://aboutus.ft.com/corporate-information/#axzz3rajCSIAt>"), 
registered office at Number One Southwark Bridge, London SE1 9HL.  
Registered in England and Wales with company number 879531. This e-mail may 
contain confidential information. If you are not the intended recipient, 
please notify the sender immediately, delete all copies and do not 
distribute it further.  It could also contain personal views which are not 
necessarily those of the FT Group.  We may monitor outgoing or 
incoming emails as permitted by law.*

**Comment by wheresrhys** [comment]
Would this work? https://github.com/Financial-Times/o-tracking/issues/93#issuecomment-162468811

**Comment by markstephens** [comment]
How would a script or application know which one to use?
I guess if `thinkOfANameForThis` is null (because data attribs don't exist) then I guess that would work.

You wouldn't do a mixture? e.g. use the data attrib if it's there, otherwise fallback to tag/class/id/whatever

`thinkOfAnotherNameForThis: 'div[0]|div[2]|article[1]#main|p[3]|o-more-ons[1]|a[2]'`

**Comment by wheresrhys** [comment]
I had a play around implementing it, and I feel that merging the two would be either
a) really verbose and difficult to parse (when always include nodeName, + o-tracking attribute if present)
b) unpredictable, fairly verbose and difficult to parse (when include node name or o-tracking attribute if present)

I like the purity of having a concise path if you play by the o-tracking rules, but also some completely unadulterated, unorigamified data available too

**Comment by adgad** [comment]
Has there been any more thought or movement on this?  We're currently working on a static HTML template for paid posts (hosted/made by third parties), and want to get dwell time and scroll depth metrics.

Would be great if this was part of o-tracking (or available via the build service somehow) rather than having to copy/paste some code around :)

**Comment by markstephens** [comment]
Hi @adgad 

Yes, I agree having to copy and paste code isn't very helpful!
There have also been calls to make o-tracking implementation on websites easier, by providing a single script url instead of all the lines, e.g. `<script src="o-tracking-for-your-website.js"></script>`

Similar is your attention time metric, where and how is that deployed?

Mark

**Comment by kavanagh** [comment]
Is this going to happen in the near future? We'd like to have all these features on IG pages.

I don't think it would be manageable for us to maintain something like n-instrumentation and try to keep it in sync so that Lantern and Beacon work.

**Comment by markstephens** [comment]
I think all these little bits have been written, we just need a place to put them and make them the standard.
The questions above around dom paths etc have been resolved within the recent click spec.

My opinion is to to put it all into an Origami component and make people consume it alongside o-tracking. That would keep o-tracking concise when it's used in different ways, and the use of Origami for these bits should standardise them.
Is that the best route? Can people who know about this stuff suggest other options if not?

**Comment by kavanagh** [comment]
Why not just include it all and have it off by default?

Having it in the library would encourage greater use of the features, more standardisation and reduce complexity. It doesn't seem like it would make the library much bigger.

**Comment by markstephens** [comment]
Yes, could do that.

**Comment by JakeChampion** [comment]
It looks like all the features which were requested back when this issue was opened in 2015 have since been added to o-tracking and we forgot to close this issue.
